#!/usr/bin/lua

local util = require("luci.util")
local fs = require("luci.fs")
local ltn12 = require 'luci.ltn12'
local sys = require("luci.sys")
local json = require("luci.json")
local nixio = require 'nixio'
local platform_info = require("platform_info")

local hostname = sys.hostname()
local model = platform_info.get_model()
local release = util.trim(fs.readfile("/lib/gluon/release") or "")
local ownername = util.trim(util.exec('uci get gluon-node-info.@owner[0].name' or "Freifunk Rheinbach"))
local ownerpage = util.trim(util.exec('uci get gluon-node-info.@owner[0].homepage' or "http://freifunk-rheinbach.de"))

function escape_html(s)
  return (s:gsub('&', '&amp;'):gsub('<', '&lt;'):gsub('>', '&gt;'):gsub('"', '&quot;'))
end

io.write("Content-type: text/html\n\n")
io.write("<!DOCTYPE html>\n")
io.write("<html>\n")
io.write("<head>\n")
io.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/styles.css\" />\n")
io.write("<title>" .. escape_html(hostname) .. "</title>\n")
io.write("</head>\n")
io.write("<body>\n")

io.write('<div class="vcard">\n')
io.write('<div class="vcard-head">Freifunk Rheinbach</div>\n')
io.write('<p class="vcard-router-name">' .. escape_html(hostname) .. '</p>\n')
io.write('<p>Dieser Router wird zur Verf&uuml;gung gestellt von:<p>\n')
io.write('<div class="vcard-router-owner"><a href="' .. escape_html(ownerpage) .. '">' .. escape_html(ownername) .. '</a></div>\n')
io.write('<div class="vcard-community">Wir freuen uns &uuml;ber einen Besuch und einen Like auf unseren Freifunk Community Seiten auf <ul><li><a href="http://freifunk-rheinbach.de">freifunk-rheinbach.de</a> oder </li>\n')
io.write('<li><a href="https://www.facebook.com/freifunkrheinbach/?ref=hl">Facebook</a></li></ul></div>\n')
io.write('<p class="vcard-router-status">Zum <a href="/cgi-bin/status" target=_blank">Routerstatus</a>.</p>')
io.write('</div>\n')
io.write('</body>\n')
io.write('</html>')
